# Generated by Django 4.1.3 on 2022-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
