# Generated by Django 4.1.3 on 2023-01-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedsession',
            name='department',
            field=models.ManyToManyField(blank=True, to='mainapp.department'),
        ),
    ]
