# Generated by Django 4.1.3 on 2023-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_admittedsession_order_alter_student_admitted_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedsession',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
