# Generated by Django 4.1.3 on 2022-11-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_student_admitted_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncompleted',
            name='session_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.admittedsession'),
        ),
    ]
