# Generated by Django 4.1.3 on 2023-02-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_admittedsession_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgpa',
            old_name='session_title',
            new_name='session',
        ),
    ]
