# Generated by Django 4.1.3 on 2022-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_sessioncompleted_session_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioncompleted',
            name='session_title',
        ),
        migrations.AddField(
            model_name='sessioncompleted',
            name='session_title',
            field=models.ManyToManyField(to='mainapp.admittedsession'),
        ),
    ]
