# Generated by Django 4.1.3 on 2022-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_sessioncompleted_session_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ManyToManyField(to='mainapp.admittedsession'),
        ),
    ]
