# Generated by Django 4.1.3 on 2023-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_cgpa_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedsession',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, unique=True),
        ),
    ]
