# Generated by Django 4.1.3 on 2022-11-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_course_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='session',
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.admittedsession'),
        ),
    ]
