# Generated by Django 4.1.3 on 2022-11-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_course_session_course_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.admittedsession'),
        ),
    ]
