# Generated by Django 4.1.3 on 2022-11-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_semester_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioncompleted',
            name='session_title',
        ),
        migrations.AddField(
            model_name='sessioncompleted',
            name='session_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.admittedsession'),
        ),
    ]
