# Generated by Django 4.1.3 on 2022-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_semester_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
