# Generated by Django 4.1.3 on 2022-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_department_admittedsession_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedsession',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.department'),
        ),
    ]
