# Generated by Django 4.1.3 on 2022-12-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_student_admitted_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.department'),
        ),
    ]
